### ISSUE TITLE
Which lxml parser is required?

### ISSUE THREAD

**Issue by lucasdurand** [relytb/tinder#3]
Standard tutorial setup, specify facebook auth info in config and run

```
Traceback (most recent call last):
  File "auto_swipe.py", line 47, in <module>
    profiles = getRecs()
  File "/home/durand/dev/tinder/api.py", line 76, in getRecs
    request = _handleHttpError(lambda x: requests.get(TINDER_URL + RECS_URI, headers=x))
  File "/home/durand/dev/tinder/api.py", line 36, in _handleHttpError
    getAuthToken()
  File "/home/durand/dev/tinder/api.py", line 53, in getAuthToken
    fb_config.init()
  File "/home/durand/dev/tinder/fb_config.py", line 13, in init
    fb_access_token = fb_auth_token.get_fb_access_token(fb_username, fb_password)
  File "/home/durand/dev/tinder/fb_auth_token.py", line 13, in get_fb_access_token
    f = s.get_form()
  File "/home/durand/.virtualenvs/tinder-h-rZUJ30/lib/python3.6/site-packages/robobrowser/browser.py", line 293, in get_form
    form = self.find(_form_ptn, *args, **kwargs)
  File "/home/durand/.virtualenvs/tinder-h-rZUJ30/lib/python3.6/site-packages/robobrowser/browser.py", line 144, in find
    return self.parsed.find
  File "/home/durand/.virtualenvs/tinder-h-rZUJ30/lib/python3.6/site-packages/robobrowser/browser.py", line 138, in parsed
    return self.state.parsed
  File "/home/durand/.virtualenvs/tinder-h-rZUJ30/lib/python3.6/site-packages/werkzeug/utils.py", line 73, in __get__
    value = self.func(obj)
  File "/home/durand/.virtualenvs/tinder-h-rZUJ30/lib/python3.6/site-packages/robobrowser/browser.py", line 40, in parsed
    features=self.browser.parser,
  File "/home/durand/.virtualenvs/tinder-h-rZUJ30/lib/python3.6/site-packages/bs4/__init__.py", line 198, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Comment by lucasdurand** [comment]
Just needs lxml to be installed as well: `pip install lxml` 
Suggest adding it to the README.md for required libs, or better yet providing a requirements/packages.txt or Pipenv file!
